# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
# Copyright 2023-2025 vLLM Team
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
"""
Generates a dictionary with _ModelInfo data classes.
"""

import argparse
import importlib
import os
import sys
import traceback
from dataclasses import fields
from pathlib import Path


def _build_model_info_dict() -> dict:
    from vllm.model_executor.models.registry import _VLLM_MODELS, _ModelInfo

    model_info_dict = {}
    for arch, (mod_relname, cls_name) in _VLLM_MODELS.items():
        try:
            mod = getattr(
                importlib.import_module(
                    f"vllm.model_executor.models.{mod_relname}"),
                cls_name,
            )
            model_info_dict[cls_name] = _ModelInfo.from_model_cls(mod)
        except Exception:
            print("-----------------------------------------")
            traceback.print_exc()
            print("-----------------------------------------")

    return model_info_dict


def _compare_model_infos(model_info_dict: dict) -> bool:
    try:
        from vllm.model_executor.models._model_info import _MODEL_INFO_DICT
    except Exception:
        _MODEL_INFO_DICT = {}

    l1 = len(_MODEL_INFO_DICT)
    l2 = len(model_info_dict)
    if l1 != l2:
        print(f"_ModelInfo dictionaries length changed {l1} != {l2}")
        return False

    for key, value in _MODEL_INFO_DICT.items():
        if key not in model_info_dict:
            print(f"new _ModelInfo dictionary removed key {key}")
            return False
        if value != model_info_dict[key]:
            print(f"_ModelInfo dictionaries changed _ModelInfo {key}")
            return False

    return True


def _build_dict_content(left_padding: int, model_info_dict: dict) -> str:
    content = ""
    sep = ""
    for cls_name, model_info in model_info_dict.items():
        content += sep
        left_str = " " * left_padding
        model_info_name = "_ModelInfo("
        padding = left_padding + len(model_info_name)
        content += f'{left_str}"{cls_name}":\n'
        content += f"{left_str}{model_info_name}"
        content += f"{_build_model_info_str(padding, model_info)})"
        sep = ",\n"

    return content


def _build_model_info_str(left_padding: int, modelinfo) -> str:
    content = ""
    sep = ""
    left_str = ""
    for field in fields(modelinfo):
        content += sep
        value = getattr(modelinfo, field.name)
        if isinstance(value, str):
            value = f'"{value}"'

        content += f"{left_str}{field.name}={value}"
        left_str = " " * left_padding
        sep = ",\n"

    return content


def _main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawTextHelpFormatter,
        description="Generate model info dictionary file",
    )
    parser.add_argument(
        "-l",
        "--local",
        default=False,
        action="store_true",
        help="Loads vLLM from local repository",
    )
    args = parser.parse_args()

    if args.local:
        # add local vLLM to path
        repo_path = os.path.abspath(
            os.path.join(os.path.dirname(__file__), ".."))
        sys.path.insert(0, repo_path)

    model_info_dict = _build_model_info_dict()
    if _compare_model_infos(model_info_dict):
        print("Model Info dictionary didn't change.")
        return

    content = "# SPDX-License-Identifier: Apache-2.0\n"
    content += (
        "# SPDX-FileCopyrightText: Copyright contributors to the vLLM project\n"
    )
    content += "# Copyright 2023-2025 vLLM Team\n"
    content += (
        '# Licensed under the Apache License, Version 2.0 (the "License");\n')
    content += (
        "# You may not use this file except in compliance with the License.\n")
    content += "# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0\n"
    content += "#\n"
    content += (
        f"# This file was automatically generated by '{Path(__file__).name}'\n"
    )
    content += "# It should not be changed manually.\n\n"

    content += "# yapf: disable\n\n"

    content += "from .registry import _ModelInfo\n\n"
    content += "_MODEL_INFO_DICT = {\n"

    content += _build_dict_content(4, model_info_dict) + "\n}"

    model_info_path = Path(__file__).parent.parent
    model_info_path = (model_info_path.joinpath("vllm").joinpath(
        "model_executor").joinpath("models"))
    model_info_file = model_info_path.joinpath("_model_info.py")

    model_info_file.write_text(content)

    print(f"Updated file {model_info_file}")


if __name__ == "__main__":
    try:
        _main()
        sys.exit(0)
    except Exception:
        traceback.print_exc()
        sys.exit(1)
